-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 20:04:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_project` DEFAULT CHARACTER SET utf8 ;
USE `test_project` ;

-- -----------------------------------------------------
-- Table `test_project`.`bgbcms_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_project`.`bgbcms_feature` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(30) NOT NULL COMMENT '推荐位名称',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '0 关闭\n1 正常\n-1 删除',
  `description` VARCHAR(100) NULL,
  `create_time` INT(10) NOT NULL,
  `update_time` INT(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COMMENT = '推荐位表';


-- -----------------------------------------------------
-- Table `test_project`.`bgbcms_feature_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_project`.`bgbcms_feature_content` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `feature_id` INT UNSIGNED NOT NULL COMMENT '推荐位ID',
  `title` VARCHAR(50) NOT NULL,
  `thumb` VARCHAR(100) NOT NULL COMMENT '缩略图URI',
  `url` VARCHAR(100) NULL DEFAULT NULL COMMENT '对应某个链接',
  `article_id` MEDIUMINT UNSIGNED NOT NULL COMMENT '对应的文章ID',
  `order` TINYINT NOT NULL DEFAULT 0 COMMENT '排序',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '0 关闭\n1 正常\n-1 删除',
  `create_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `update_time` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
